SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)
DEP = $(OBJ:.o=.d)
CC = gcc
CFLAGS = -Wall -DWINDOWS -g -DINSTRUMENTED -DRANGECHECK
LDFLAGS = -lmingw32 -lgdi32 -lkernel32 -luser32 -mwindows -lSDL2main -lSDL2 -lSDL2_mixer -lSDL2_net

reboom: $(OBJ)
	$(CC) -o $@ $^ $(LDFLAGS)

-include $(DEP)

%.d: %.c
	@$(CPP) $(CFLAGS) $< -MM -MT $(@:.d=.o) >$@

.PHONY: clean
clean:
	del $(OBJ) $(DEP) reboom
