SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)
DEP = $(OBJ:.o=.d)
CC = gcc
CFLAGS = -std=c2x -pedantic -Wall -DWINDOWS
LDFLAGS = -lmingw32 -lgdi32 -lkernel32 -luser32 -mwindows -lSDL2main -lSDL2 -lSDL2_mixer -lSDL2_net -lSDL2_image

reboom: $(OBJ)
	$(CC) -o $@ $^ $(LDFLAGS) win32/reboom.res

icon:
	windres win32/reboom.rc -O coff -o win32/reboom.res

-include $(DEP)

%.d: %.c
	@$(CPP) $(CFLAGS) $< -MM -MT $(@:.d=.o) >$@

.PHONY: clean
clean:
	del $(OBJ) $(DEP) reboom
